# Site settings
title_left    : "Manus"
title_right   : "blog" # default: ""
description   : "Travelling - Software Development - Digital Nomadism"
keywords      : "software, development, digital, nomad, travel, travelling"
url           : https://manuelgerstner.github.io/ # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-XXXXX-XX
twitter_username  : "manuelgerstner"
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name      : "Manuel Gerstner"
  location  : Munich
  voice     : +49 173 570 3426

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
