# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Manuel Gerstner
email: manuelgerstner@gmail.com
description:  Hi, my name is Manuel. I am Software Developer and Cloud Architect, currently based somewhere between GMT and GMT+2 (Europe / Africa).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.myhappyisland.com" # the base hostname & protocol for your site
twitter_username: manuelgerstner
github_username:  manuelgerstner

# Build settings
markdown: kramdown
